name: Build and package eSASS4DR1

env:
  ESASS_VERSION: "1.0.2"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build eSASS4DR1 (${{ matrix.os }}/${{ matrix.target-platform }}, HEASoft ${{ matrix.heasoft }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            target-platform: linux-64
            heasoft: "6.35.*"
            # GCC version
            c-compiler-version: "15.0.*"
            cxx-compiler-version: "15.0.*"
            fortran-compiler-version: "15.0.*"
          - os: ubuntu-latest
            target-platform: linux-64
            heasoft: "6.36.*"
            # GCC version
            c-compiler-version: "15.*"
            cxx-compiler-version: "15.*"
            fortran-compiler-version: "15.2.*"

          # MacOS ARM builds (macos-latest is ARM64)
          - os: macos-latest
            target-platform: osx-arm64
            heasoft: "6.35.*"
            # clang versions and gfortran version
            c-compiler-version: "20.*"
            cxx-compiler-version: "20.*"
            fortran-compiler-version: "==14.2.0"
          - os: macos-latest
            target-platform: osx-arm64
            heasoft: "6.36.*"
            # clang versions and gfortran version
            c-compiler-version: "22.*"
            cxx-compiler-version: "22.*"
            fortran-compiler-version: "15.*"

          # MacOS Intel builds (using macos-26-intel, the latest and last Intel version)
          - os: macos-26-intel
            target-platform: osx-64
            heasoft: "6.35.*"
            # clang versions and gfortran version
            c-compiler-version: "20.*"
            cxx-compiler-version: "20.*"
            fortran-compiler-version: "==14.2.0"
          - os: macos-26-intel
            target-platform: osx-64
            heasoft: "6.36.*"
            # clang versions and gfortran version
            c-compiler-version: "22.*"
            cxx-compiler-version: "22.*"
            fortran-compiler-version: "15.*"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Format artifact name
        id: format_name
        run: |
          # Replace * with all and . with _
          HEASOFT_NAME=$(echo "${{ matrix.heasoft }}" | sed 's/\*/all/g; s/\./_/g')
          echo "heasoft_name=$HEASOFT_NAME"
          echo "heasoft_name=$HEASOFT_NAME" >> $GITHUB_OUTPUT

      - name: Increase file limits (Linux/macOS)
        run: |
          ulimit -n 16000 || true
          echo "Current file limits:"
          ulimit -a

      - name: Build package
        uses: prefix-dev/rattler-build-action@v0.2.39
        with:
          recipe-path: recipe/recipe.yaml
          build-args: |
            --channel https://heasarc.gsfc.nasa.gov/FTP/software/conda \
            --channel conda-forge \
            --variant version=${{ env.ESASS_VERSION }} \
            --variant heasoft_version=${{ matrix.heasoft }} \
            --variant c-compiler-version=${{ matrix.c-compiler-version }} \
            --variant cxx-compiler-version=${{ matrix.cxx-compiler-version }} \
            --variant fortran-compiler-version=${{ matrix.fortran-compiler-version }} \
            --target-platform ${{ matrix.target-platform }} \
          upload-artifact: true
          artifact-name: ${{ matrix.target-platform }}_esass4dr1-${{ env.ESASS_VERSION }}-heasoft${{ steps.format_name.outputs.heasoft_name }}
