name: eSASS4DR1 installation page monitor

on:
  schedule:
    - cron: '00 13 * * 2' # Runs every Tuesday at 1pm
      timezone: "America/Detroit"
  workflow_dispatch:

jobs:
  webchanges:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # So issues can be opened

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7

      - name: Restore snapshots database
        uses: actions/cache@v6
        with:
          path: snapshots.db
          key: snapshots-db-${{ github.run_id }}
          restore-keys: |
            snapshots-db-

      - name: Webpage change detector
        uses: swimmwatch/webchanges-action@v1.0.1
        with:
          jobs: |
            name: eSASS4DR1 page monitor
            url: https://erosita.mpe.mpg.de/dr1/eSASS4DR1/eSASS4DR1_installation/
            use_browser: false
          config: |
            report:
              github_issue:
                enabled: true
                owner: "${{ github.repository_owner }}"
                repo: "${{ github.event.repository.name }}"
                token: "${{ secrets.GITHUB_TOKEN }}"
                title: "eSASS4DR1 installation page change detected: {dt}"
